### ISSUE TITLE
AutoPilot info only works on Windows Powershell 5.1?

### ISSUE THREAD

**Issue by persalmi** [tabs-not-spaces/Intune.USB.Creator#1]
I tried to run the USB creation from pwsh 7 but then I never get the AutoPilot / Intune sign-in and profile selection to work. It just skips the admin login and profile selection and continues reporting that the json file does not exist. But it works if I run the Publish-ImageToUSB from an admin Windows Powershell 5.1 prompt.
As this seems to differ from your clip running the process from pwsh 7 there must be something I am missing on my machine?

**Comment by tabs-not-spaces** [comment]
Hey Per,

Make sure you are using the latest build - the required dependencies may
need to download to the pwsh7 module location which has only been added in
the last 48 hours.

I've just re-ran the module on a few test devices and am 100% getting the
prompt for auth to Azure, so without knowing your environment it's
difficult for me to identify the issue!

Cheers,

Ben

**Comment by tabs-not-spaces** [comment]
also, technically, yes the ADAL libraries that the required dependency modules use don't work in 7, but I've got logic in place to allow backwards compatibility.

https://github.com/tabs-not-spaces/Intune.USB.Creator/blob/2ff0fd3de3bed180b749593512da25005c72bf8c/Intune.USB.Creator/Private/Get-AutopilotPolicy.ps1#L11-L24

The only trick is that you NEED the modules in both your 7 & 5.1 module locations for this to work - which is resolved by making sure you install the latest module in the environment you want to use as it should pull down the missing modules..

**Comment by persalmi** [comment]
Ok, I didn't have the modules installed under 5.1 at first but it did work when running the whole USB creation process under 5.1.
