### ISSUE TITLE
Image Index and Partition as Parameters

### ISSUE THREAD

**Issue by axgch** [tabs-not-spaces/Intune.USB.Creator#14]
Hi, I'm trying to automate the creation of new USBs in my company with your tool with a pipeline, but in order to do that, I need to pass the Image Index and the Partition as parameters. This is very useful to not be dependent on anyone's computer to build new USBs.

**Comment by tabs-not-spaces** [comment]
Really good idea - I'll knock together something shortly. ☕

**Comment by tabs-not-spaces** [comment]
@axgch - I've added a new <code>-ImageIndex</code> parameter to the solution. Build from the steps below and let me know if this suits your requirements.

## Build Steps

- Check out the <code>ImageIndexer</code> branch - https://github.com/tabs-not-spaces/Intune.USB.Creator/tree/ImageIndexer
- From the root of the project, in PowerShell, run the build script

``` PowerShell
.\build.ps1 -modulePath .\Intune.USB.Creator -moduleName Intune.USB.Creator -buildLocal
```

- Import the newly built module (replease *buildId* with the build number that is generated)

``` PowerShell
Import-Module .\bin\release\*buildId*\Intune.USB.Creator
```

- Test away!

## Notes

the <code>-ImageIndex</code> parameter takes an Integer input - make sure you know which image index / edition number you want.

---

Let me know you go 🚀
