### ISSUE TITLE
Writing WinPE to USB.. does nothing

### ISSUE THREAD

**Issue by eichmeyer** [tabs-not-spaces/Intune.USB.Creator#17]
No data is copied in the 'Writing WinPE to USB' section. 
A folder is created on the 'Images' partition and the install.wim is copied.

![image](https://user-images.githubusercontent.com/36456013/88476468-dc568f80-cf38-11ea-8e35-b3ffc8d8169f.png)

**Comment by eichmeyer** [comment]
Get-RemoteFile -fileUri $winPEPath -destination $usb.downloadPath -expand
unpacks WinPE.zipfile to 'temp\Win10\W' and not to 'temp\Win10\WinPE'. Therefore the files are not found.

**Comment by eichmeyer** [comment]
After I renamed the folder under Temp to WinPE, the script works:

![image](https://user-images.githubusercontent.com/36456013/88476714-f2fde600-cf3a-11ea-9381-714721638ca1.png)

**Comment by tabs-not-spaces** [comment]
If possible could you provide the full command used to start this off?

Just need to know the parameter values so I can try and replicate.

Cheers.

**Comment by eichmeyer** [comment]
Publish-ImageToUSB -winPEPath "https://githublfs.blob.core.windows.net/storage/WinPE.zip" -windowsIsoPath "D:\Hyper-V\ISO\de_windows_10_consumer_editions_version_2004_updated_july_2020_x64_dvd_a3933985.iso" -getAutopilotCfg

**Comment by tabs-not-spaces** [comment]
PowerShell 7 or 5.1???

**Comment by eichmeyer** [comment]
PowerShell 5.1
under 7 the WindowsAutoPilot will not provide the AutopilotConfigurationFile.json
