### ISSUE TITLE
device not provisioning

### ISSUE THREAD

**Issue by belacs** [tabs-not-spaces/Intune.USB.Creator#19]
Hello,
im hoping you can help me. I ran the tool and chose a autopilot profile when the system boots up and i sign in it says wait while we configure then it sits there for a long time and then gets error "something went wrong. confirm you are using the correct sign-in information and that your organization uses this feature. you can try to do this again or contact your sys admin with error code 80070002. 
we have A5 licenses,  and i can see the device in enrolment manager. 
when i look at hte event log on the device this is one of the few errors. I have been talking to MS but they have not helped with any actual troubleshooting yet, just listened to them complain for about an hour that using a usb is unusual.

Log Name:      Microsoft-Windows-DeviceManagement-Enterprise-Diagnostics-Provider/Admin
Source:        Microsoft-Windows-DeviceManagement-Enterprise-Diagnostics-Provider
Date:          8/24/2020 1:57:51 PM
Event ID:      404
Task Category: None
Level:         Error
Keywords:      
User:          SYSTEM
Computer:      DESKTOP-E43PIMM
Description:
MDM ConfigurationManager: Command failure status. Configuration Source ID: (196EB1CE-94DC-4FA0-9D15-EFEB3A15B8AD), Enrollment Name: (MDMDeviceWithAAD), Provider Name: (Policy), Command Type: (Add: from Replace or Add), CSP URI: (./Device/Vendor/MSFT/Policy/ConfigOperations/ADMXInstall/Receiver/Properties/Policy/FakePolicy/Version), Result: (The system cannot find the file specified.).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-DeviceManagement-Enterprise-Diagnostics-Provider" Guid="{3da494e4-0fe2-415c-b895-fb5265c5c83b}" />
    <EventID>404</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2020-08-24T20:57:51.321585500Z" />
    <EventRecordID>510</EventRecordID>
    <Correlation />
    <Execution ProcessID="8644" ThreadID="6580" />
    <Channel>Microsoft-Windows-DeviceManagement-Enterprise-Diagnostics-Provider/Admin</Channel>
    <Computer>DESKTOP-E43PIMM</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="Message1">196EB1CE-94DC-4FA0-9D15-EFEB3A15B8AD</Data>
    <Data Name="Message2">MDMDeviceWithAAD</Data>
    <Data Name="Message3">Policy</Data>
    <Data Name="InternalCmdType">1</Data>
    <Data Name="Message5">./Device/Vendor/MSFT/Policy/ConfigOperations/ADMXInstall/Receiver/Properties/Policy/FakePolicy/Version</Data>
    <Data Name="HexInt1">0x80070002</Data>
  </EventData>
</Event>

**Comment by belacs** [comment]
the other weir thing is i have run the process a few times and it actually adds a new device each time, i did not think that was possible.

**Comment by belacs** [comment]
i think there is just some thing simple i am missing. tried the whiteglove option and it says "Deployment profile: no profile found" but i chose the profile when i made the usb.

**Comment by tabs-not-spaces** [comment]
Hey belacs,

Doesn't sound like an issue with the code base, so I'm going to have to
close this issue out.

As far as troubleshooting the experience you are having, I'd start by just
trying the process of capturing the hardware hash manually first.

Make sure there are no device objects in AAD or Intune with the serial
number of your device (it's entirely normal for duplicate objects to appear
in Intune - each time you reimage the device it's seen as a new one in the
Intune space).

Without knowing how your environment is configured, there's little more I
can suggest, as there could be multiple things blocking you from using this
"offline autopilot" method.

If you want to discuss further, hit me up on twitter @powers_hell.

**Comment by belacs** [comment]
i understand.  thanks for the info and this tool! :)
