### ISSUE TITLE
 Requires tenant to allow enrollment of personally owned devices to work? 

### ISSUE THREAD

**Issue by persalmi** [tabs-not-spaces/Intune.USB.Creator#2]
Is it mandatory to have the enrollment restrictions set to allow personally owned devices to enroll for the autopilot enrollment part to work? Seems like it fails with an 80180014 error if personally owned devices are blocked.

**Comment by BenStreet365** [comment]
I can’t recreate this problem and I have personal devices blocked too, are you doing Cloud or Hybrid autopilot?

**Comment by persalmi** [comment]
Must be categorized as cloud, the AAD is synced with an ordinary AD but the client pc and and user does not use anything else than internet connection working from home and the AAD / 365 sign in.

Maybe some other setting that causes the error then, as the personally owned permission works for you. I can not test with it allowed.

The USB is created with an autopilot json file but it does not work when the client pc is installed and tries to register to the tenant. 

Any tips on where to start looking for the error? 

/Per

**Comment by BenStreet365** [comment]
I'll try again tomorrow, but I had a thought. Have you tried the image you've created on a new Virtual Machine? Thinking if the device has been previously registered there may be some issue in Azure AD.

**Comment by persalmi** [comment]
The machine I tested with had been joined before but removed from the device list and from all groups and from the AAD before testing the image. Will test with a VM and see if that works better. Also got another laptop that has not been registered with the AAD to try in a few days so it might show a better outcome.

**Comment by BenStreet365** [comment]
Hopefully it will, I've tested on a couple of VMs and can't get that error

**Comment by tabs-not-spaces** [comment]
Let me know how you go with this, but as far as I can tell the issue you are experiencing is external to this module, so I'm going to close the issue.
