### ISSUE TITLE
Multiple request is not supported errors

### ISSUE THREAD

**Issue by SharirAG** [tabs-not-spaces/Intune.USB.Creator#23]
Hi,

After creating the USB and pluging it in to multiple laptops. i get a warning: The request is not supported.

this happens when setting the power policy , we have fixed this by editing the invoke-provision.ps1 file:

```
        switch ($powerPlan) {
            PowerSaver {
                Write-Host "Setting power policy to 'Power Saver'.." -ForegroundColor Cyan
                $planGuid = "a1841308-3541-4fab-bc81-f71556f20b4a"
            }
            Balanced {
                Write-Host "Setting power policy to 'Balanced'.." -ForegroundColor Cyan
                $planGuid = "381b4222-f694-41f0-9685-ff5bb260df2e"
            }
            HighPerformance {
                Write-Host "Setting power policy to 'High Performance'.." -ForegroundColor Cyan
                $planGuid = "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"
            }
            default {
                throw "Incorrect selection.."
            }
        }
        Invoke-CmdLine -application powercfg -argumentList "/s $planGuid" -silent
    }
    catch {
        Write-Host $_.Exception.Message -ForegroundColor Red
```

after this edit, the usb continued to the next step.

but at the setting install.wim location
we  got the another Warning: The request is not supported.

![WhatsApp Image 2020-11-26 at 15 04 31](https://user-images.githubusercontent.com/14299181/100393119-e4ceec00-3038-11eb-9d14-4813c72446c1.jpeg)
![WhatsApp Image 2020-11-26 at 15 44 54](https://user-images.githubusercontent.com/14299181/100393120-e5678280-3038-11eb-99c2-3aed049cc608.jpeg)

USB has been built successfully
![image](https://user-images.githubusercontent.com/14299181/100393146-f9ab7f80-3038-11eb-81e6-c3faab7c8ebd.png)

**Comment by tabs-not-spaces** [comment]
Yep as mentioned in issue #22 it's an issue with PowerShell 7.

I'm looking into a solution to specify the build version that gets pulled
down.

**Comment by tabs-not-spaces** [comment]
As this is a duplicate issue, I will close

**Comment by SharirAG** [comment]
thansk for the quick response.

is there anything we can do at the moment to bypass this problem?

**Comment by tabs-not-spaces** [comment]
duplicate issue to #22 which has since been resolved.

**Comment by SharirAG** [comment]
Hi,

I've used the updated script, but i still get the same error.

Anythng I can do, to help troubleshooting?
