### ISSUE TITLE
error running script

### ISSUE THREAD

**Issue by rikkimantha** [tabs-not-spaces/Intune.USB.Creator#3]
Writing Autopilot to USB..

WARNING: You cannot call a method on a null-valued expression.

Grabbing provision script from GitHub..
WARNING: Could not find a part of the path 'D:\scripts\Invoke-Provision.ps1'.

**Comment by BenStreet365** [comment]
Hey,

This may or may not be helpful, but I had a similar problem and didn't really investigate. I installed Visual Studio 2019 Community Edition with a couple tools I'm trying (Azure Development being one of them) and it works again :)

**Comment by tabs-not-spaces** [comment]
@rikkimantha was this error produced from the release in the gallery, or from the source in this repository?

I'm working on some changes and that second block shouldn't be coming up if using the production release..

**Comment by tabs-not-spaces** [comment]
As noone is reporting this issue, im going to close it unless you have any further problems
