### ISSUE TITLE
Option to use this script for PXE Boot

### ISSUE THREAD

**Issue by FaserF** [tabs-not-spaces/Intune.USB.Creator#31]
As there are no Discussions here I am asking that question as an issue. I hope that this is okay.

Your Tool works awesome for a USB Drive provisioning! Thanks for that.
I tried to use these WinPE files for provisioning windows via PXE Boot, unfortunatly the script ends because it "cant detect the USB Drive letter" which makes sense. 
Do you have any plans for supporting a PXE setup? If not I will try to go through your powershell files and find my not beautiful way to do this 🗡️ 

Thanks in advance!

**Comment by tabs-not-spaces** [comment]
Haven't looked into pxe as this isn't the scope or point of the solution.
But would be cool to see it implemented to work with pxe.
