### ISSUE TITLE
PID.txt serial key slipstream?

### ISSUE THREAD

**Issue by chaoscreater** [tabs-not-spaces/Intune.USB.Creator#33]
I've tried putting the PID.txt into the Sources folder, but it doesn't get applied. How can we slipstream the serial key into the image using your build method?

https://dellwindowsreinstallationguide.com/windows-8/windows-8-1-adding-the-ei-cfg-and-pid-txt/

**Comment by tabs-not-spaces** [comment]
This isn't implemented as there are better solutions for OS licensing tied to the user account.
If it's something you want added, go for it.
