### ISSUE TITLE
Grabbing Autopilot config file from Azure

### ISSUE THREAD

**Issue by glwheeler** [tabs-not-spaces/Intune.USB.Creator#35]
When grabbing Autopilot config file from Azure.., I get this.
WARNING: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

**Comment by macaddict89** [comment]
I had this issue today on a new machine.  When I was trying some troubleshooting I tried to run a command and found the issue to be that I hadn't changed the executionpolicy settings. It may not be your issue, however I wanted to post this in case someone else hadn't checked executionpolicy settings.

**Comment by tabs-not-spaces** [comment]
The issue is due to not having the msal module in both PowerShell 5.1 and
PowerShell 7.0 module locations.

**Comment by macaddict89** [comment]
That checks out. I had installed the module in 5.1 as part of my troubleshooting so i may have been off on my resolution.

**Comment by glwheeler** [comment]
Thanks

**Comment by gregfink83** [comment]
I am getting this error as well.  I'm sorry I don't understand the fix, can some be more descriptive?  Thank you.

**Comment by tabs-not-spaces** [comment]
It's not an error. Install the MSAL.PS module for both PowerShell 5.1 & PowerShell 7.0.
