### ISSUE TITLE
Lenovo Network Drivers don't Load

### ISSUE THREAD

**Issue by glwheeler** [tabs-not-spaces/Intune.USB.Creator#38]
We have Lenovo T14's and the network drivers do not load with Windows 10. Do I have to add the drivers to the .iso?

**Comment by tabs-not-spaces** [comment]
No.

As implemented in 2776eff7ef3f8bfafe97088ad7cb9e2664b744ec, there should be a folder in the root of one of the partitioned named drivers (I can't remember which one. its 3am). Put any required drivers in there and it should bootstrap them into the build.

**Comment by glwheeler** [comment]
Thanks

**Comment by glwheeler** [comment]
It just gets stuck on this screen. 
![20210624_140737](https://user-images.githubusercontent.com/15280275/123312886-e8572280-d4f6-11eb-88e5-ca2ca4eb4fd5.jpg)

**Comment by tabs-not-spaces** [comment]
So, shift+F10 into console, open device manager and verify if the drivers
have been loaded.

**Comment by glwheeler** [comment]
The folder worked. Thank you for your help.

**Comment by glwheeler** [comment]
Now it is stuck on this screen.

![20210701_095847](https://user-images.githubusercontent.com/15280275/124138072-4d110080-da54-11eb-9aef-513e835c042d.jpg)

**Comment by glwheeler** [comment]
Do you do consulting work with Endpoint?
