### ISSUE TITLE
Check Size of USB device before letting use it

### ISSUE THREAD

**Issue by JigSawFr** [tabs-not-spaces/Intune.USB.Creator#4]
Hello,
Thank you for your hard work, it's a pretty nice tool !

As improvement, it could be great to check size of USB devices before letting select one,
So, we avoid errors due to USB device not meeting minimum space requirement.
An prevent us if it doesn't meet expectation :)

Thank you

**Comment by tabs-not-spaces** [comment]
Good idea - would make a good good first issue if you felt like contributing
