### ISSUE TITLE
Error While Getting Deviceid of Potential Windows Target Drives

### ISSUE THREAD

**Issue by smithtrev** [tabs-not-spaces/Intune.USB.Creator#44]
I got the following error while trying to run Intune USB Creator on an Lenovo e14 ITL.
Error while getting deviceid of potential windows target drives

**Comment by smithtrev** [comment]
The solution was to grab the storage drivers for the model of computer from the manufacturer website and add them to the drivers folder of the Images partition of the USB.

**Comment by russ-estes** [comment]
Getting the same error message on a Dell Latitude 3520. I added the Intel storage drivers to the Drivers folder of the Images partition on the USB, but get the same error. I did see the drivers load before the error.

**Comment by russ-estes** [comment]
The solution was to extract the Intel storage drivers from the installer on the Dell support staff and ALL of those to the Drivers folder of the Images partition on the USB.
