### ISSUE TITLE
diskNum flag not working

### ISSUE THREAD

**Issue by ajkenah** [tabs-not-spaces/Intune.USB.Creator#45]
When passing the diskNum flag to the Publish-ImageToUSB command, it still asks me to select which disk to use.
The following line in the "Get-DiskToUse" module should probably be updated
// From
$diskNum = Read-Host -Prompt "$table`Please select Desired disk number for USB creation or CTRL+C to cancel"

// To
If(!$diskNum){
$diskNum = Read-Host -Prompt "$table`Please select Desired disk number for USB creation or CTRL+C to cancel"
}

**Comment by tabs-not-spaces** [comment]
@ajkenah did you want to quickly look over the change below and provide feedback if required. This should not cause any major breaking changes to implement immediately.
