### ISSUE TITLE
Feedback in regards of SHA256Cng fix and missing install.wim.

### ISSUE THREAD

**Issue by vazome** [tabs-not-spaces/Intune.USB.Creator#48]
In my case, the fix for 'System.Security.Cryptography.SHA256Cng' error was not enough.

Luckily, when I installed all of the following modules it worked out. 

- [WindowsAutoPilotIntune](https://www.powershellgallery.com/packages/WindowsAutoPilotIntune)
- [Microsoft.Graph.Intune](https://www.powershellgallery.com/packages/Microsoft.Graph.Intune/)
- [MSAL.PS](https://www.powershellgallery.com/packages/MSAL.PS)

Yet still receiving an index error with install.wim.

**Comment by vazome** [comment]
I found one of the reasons "index error with install.wim" - Media Creation Tool does not supply ISO with such file.
After getting a proper ISO from - https://www.microsoft.com/en-us/software-download/windows10ISO install.wim was found and installation went proper.

![image](https://user-images.githubusercontent.com/46573198/154169177-865c180a-6873-4bf6-8c28-77e5492825d3.png)

**Comment by tabs-not-spaces** [comment]
both of things are documented already.
