### ISSUE TITLE
Error- cannot call method on a null valued expression 

### ISSUE THREAD

**Issue by harpreetgill12** [tabs-not-spaces/Intune.USB.Creator#49]
The code works fine on my old computer, however I get the following error on the new computer.

I have checked all the pre-req and execution policy is set to unrestricted.
Can you please help?

![8FAFA33E-9765-4D42-8406-B8BE622DEE6D](https://user-images.githubusercontent.com/59076846/160257257-3a32fc9a-e9ad-4027-879c-69f14bd6df5d.jpeg)

**Comment by RamboPixie1405** [comment]
Hello, I've got the exact same error, did you found what's causing it yet?

**Comment by harpreetgill12** [comment]
I have managed to fix it by placing the invoke-provision.ps1 manually in the scripts folder. You need to unzip the WinPE folder and zip it again after placing the file.
Also, make sure to clear your Temp folder 'C:\Users\user1\AppData\Local\Temp\Win10' before re-running the script.
