### ISSUE TITLE
Error getting image Index

### ISSUE THREAD

**Issue by JigSawFr** [tabs-not-spaces/Intune.USB.Creator#5]
Hello,
I've downloaded an ISO (Win 10 Enterprise) via the tool Windows Media Creation Tool.
With the script, it fail with this error:

```
Getting image index from install.wim..
WARNING: Le fichier spécifié est introuvable.
```

Is there a log file somewhere to debug ?
Thank you

**Comment by BenStreet365** [comment]
Hey,

You need an ISO from MSDN, the Media Creation Tool does not use WIM files.

Cheers

**Comment by JigSawFr** [comment]
> Hey,
> 
> You need an ISO from MSDN, the Media Creation Tool does not use WIM files.
> 
> Cheers

Thank you for reply,
I will test it, i think we need to precise it somewhere in main page to avoid errors

**Comment by JigSawFr** [comment]
Thank you this step is now working as expected !
